DB_URL=jdbc:mysql://avnadmin:AVNS_OV1Diu1FQinj4CPVUwQ@mysql-1d701bf1-maxi2594-2e20.f.aivencloud.com:26717/defaultdb?ssl-mode=REQUIRED
DB_USER=udmpzbp0biisdwg6
DB_PASS=fLAq4JNMHZO8QnR8T8fg
JWT_SECRET=tu_clave_jwt_secreta